import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/componentes/side'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Don Gestín',
  description: 'Generated by Gestines',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar></Sidebar>
        {children}
        </body> 

    </html>
  )
}
